"""add_security_questions_to_users

Revision ID: 5a152b43206f
Revises: c10944dd73a2
Create Date: 2025-07-25 05:36:38.386032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a152b43206f'
down_revision: Union[str, None] = 'c10944dd73a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('security_question_1', sa.String(), nullable=True))
    op.add_column('users', sa.Column('security_answer_1', sa.String(), nullable=True))
    op.add_column('users', sa.Column('security_question_2', sa.String(), nullable=True))
    op.add_column('users', sa.Column('security_answer_2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'security_answer_2')
    op.drop_column('users', 'security_question_2')
    op.drop_column('users', 'security_answer_1')
    op.drop_column('users', 'security_question_1')
    # ### end Alembic commands ###
