"""add_full_name_to_users

Revision ID: c01a33cace24
Revises: 5a152b43206f
Create Date: 2025-07-25 09:51:57.706200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01a33cace24'
down_revision: Union[str, None] = '5a152b43206f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_secrets_id'), table_name='admin_secrets')
    op.drop_table('admin_secrets')
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    op.create_table('admin_secrets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('secret_token', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_secrets_id'), 'admin_secrets', ['id'], unique=False)
    # ### end Alembic commands ###
