"""Add last_refreshed to documents

Revision ID: c10944dd73a2
Revises: 29f8e17a8069
Create Date: 2025-05-09 01:47:10.532742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c10944dd73a2'
down_revision: Union[str, None] = '29f8e17a8069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('last_refreshed', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_documents_last_refreshed'), 'documents', ['last_refreshed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_last_refreshed'), table_name='documents')
    op.drop_column('documents', 'last_refreshed')
    # ### end Alembic commands ###
